### ISSUE TITLE
One-click Linktree migration

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Singlelink#1]
Add one-click Profile migration from Linktree to a Singlelink user account.

Features
====================
- Highly configurable, can pull any or all of the profile as requested
- Can copy links, styles, content, and profile data
- Can copy Linktree meta data
- One click Linktree cancellation link
- One click Linktree -> Singlelink redirect

**Comment by NavidK0** [comment]
Added #183
