### ISSUE TITLE
Add Option for Email Change

### ISSUE THREAD

**Issue by Hintsmth** [Neutron-Creative/Singlelink#136]
Hello there!
It would be very helpful to add option for email change through password verification.
Thanks in advance.

**Update as of 6/22:**
- [x] Frontend (@jimmybisenius)
- [ ] Backend (@NavidK0)
- [ ] Integration (@NavidK0)

**Comment by jimmybisenius** [comment]
Great idea! I've added it to the roadmap for Singlelink v2.3.

Thank you for taking the time to make an issue!! 🥇

**Comment by jimmybisenius** [comment]
This is added in v4, closing. Send me a DM if you want to get on v4!
