### ISSUE TITLE
Idea: Create a version of the client that only contains user profile rendering

### ISSUE THREAD

**Issue by NavidK0** [Neutron-Creative/Singlelink#140]
With dockerized images, it would be possible to separate the client into two versions: One that contains the dashboard, and one that doesn't. It is also possible without containers, but docker makes this option more feasible to maintain.

This would reduce the size of the payload immensely while keeping the ease of use for hosting. The version of the client with the dashboard would remain as "app.singlelink.co", while the optimized version without the dashboard included could be hosted on a different domain, representing the optimized version.

The issues with massive payload sizes would be addressed while keeping the ability to have small pages that don't need to be exported to a static page. The images would be hosted on Kubernetes for scalability, and updated then rolled out at the same time, so nothing would be out of sync.

The optimized version of the client could be updated *mostly* automatically, so no extra maintenance is needed.

*This is just an idea, feel free to leave thoughts and comments.*

**Comment by NavidK0** [comment]
This would also resolve issues with unnecessary animations, loading bars, and weird behaviors, as well as overall speed up the end-user experience when viewing the end profile.

**Comment by jimmybisenius** [comment]
Let's discuss this more together, I had a different solution, but this seems promising!

I wonder how lean we could get both of our solutions to be.

**Comment by NavidK0** [comment]
Implemented in beta branch.
