### ISSUE TITLE
Open Deeplink explanation into new tab

### ISSUE THREAD

**Issue by shtefcs** [Neutron-Creative/Singlelink#142]
Hi guys nice work.

Just an improvement for UX, it screwed my link creation when I wanted to see what is deep link. You should open it in a new tab instead.

![](https://i.imgur.com/v0Bwu1f.png)

**Comment by jimmybisenius** [comment]
Consider this done! I'll have this patched by EOD today.

**Comment by jimmybisenius** [comment]
Thanks so much for taking the time to create an issue! 🙏

**Comment by shtefcs** [comment]
Always bro! I like to support great open projects.

Peace,

-----------------------
Stefan Smiljkovic
Co-Founder & CEO
Vanila.io, Automatio.co
(e): ***@***.***
(p): +381 62 973 4218
