### ISSUE TITLE
default authentifcation 

### ISSUE THREAD

**Issue by drkamine** [Neutron-Creative/Singlelink#160]
Hello  i just  install the server can i know the admin username and password

**Comment by jimmybisenius** [comment]
Hey, glad to help @drkamine!

There's no default "admin username & password".

Instead, you'll need to create a new user/password using the create account page located at /create-account, then you'll need to run terminal command `npm run add-admin <email>` to add this user's id to a list of "admin users" in the database.

Hope this helps!
