### ISSUE TITLE
example config.json more detail

### ISSUE THREAD

**Issue by alibaltschun** [Neutron-Creative/Singlelink#167]
hello, i wanna try running on locally using docker compose.
but when I want to fill the config.js kinda confused.

can you give me a real example of config.js with dummy variable

like 
"database":"aws.rds.............."
"secret": ( db password???)

thanks

**Comment by NavidK0** [comment]
Check out api-config.template.env in the upcoming v3 update. You can view the beta-v3 branch for now to get a peek.
