### ISSUE TITLE
Is watermark going to stay optional for free accounts?

### ISSUE THREAD

**Issue by benkaiser** [Neutron-Creative/Singlelink#175]
I see the pricing page highlights "No ads or watermarks", yet with a free account as it stands today, I can disable the watermark. Is this feature going to move into the "paid" tier once that is up and running?

Fantastic project BTW!

**Comment by jimmybisenius** [comment]
On the hosted version it is slated to be removed, but on the self-hosted variant, it will remain optional.

Thanks for all the issue reports by the way! Really helps :)

**Comment by benkaiser** [comment]
Thanks for the clarification. We're there also plans to add variants of the watermark? Would love just a logo-based one instead of the blob of text.

**Comment by jimmybisenius** [comment]
Yes, great thought @benkaiser! We're working on different watermark versions now, hope to have this released in the next major release (3.x).
