### ISSUE TITLE
Import from Linktree

### ISSUE THREAD

**Issue by benkaiser** [Neutron-Creative/Singlelink#178]
Is there a way to import a linktree profile?

The data seems very easy to pull from a linktree page (see npm library I made the other day: https://www.npmjs.com/package/linktree-scraper ).

Another option if you want to disconnect from the branding, would be to allow a "profile config import" and then have a third party service convert linktree -> singlelink. I'm happy to create PRs on this front.

**Comment by jimmybisenius** [comment]
Love this! and the npm package. Let me see what @NavidK0 (CTO) is open to regarding PRs, would love the extra hand!

**Comment by NavidK0** [comment]
Sure, go for it! Always happy to check out PRs.

**Comment by benkaiser** [comment]
Okay sounds good. I'll kick off a PR as part of the product and we can iterate from there.

**Comment by NavidK0** [comment]
Added in with #183.
