### ISSUE TITLE
Add NC-DeepLink Capability to Singlelink

### ISSUE THREAD

**Issue by drewpatrickboyle** [Neutron-Creative/Singlelink#18]
Can we get native deep links added to singlelink, @NavidK0 , @jimmybisenius ?

**Comment by NavidK0** [comment]
Added rudimentary support in the backend. Still needs a database entry + frontend UI.

**Comment by NavidK0** [comment]
Should be integrated with 4a7fd0dc7ed86c7965438bb7b702f59d3491813b in future update @drewpatrickboyle. Needs testing.
