### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by fabrizio-cantalupo** [Neutron-Creative/Singlelink#190]
I cannot find a way to delete the account in the website, even searching "site:app.singlelink.co delete account" or spending time in the settings

**Comment by jimmybisenius** [comment]
Hm, I thought this was in! Just double checked, I guess not. I'll work on a solution ASAP, but in the meantime send me an email at jim@neutroncreative.com from the email you signed up with and I can cancel it for you.

**Comment by jimmybisenius** [comment]
Delete button in on-vendor in v4.
