### ISSUE TITLE
Convert images to webp format

### ISSUE THREAD

**Issue by Ruriko** [Neutron-Creative/Singlelink#199]
I would like to see the ability to convert uploaded images to webp format cause it's 30% smaller than jpg which can save storage space. Currently I just see it render the original size avatar without converting and it just uses css to resize it which isn't good cause what if someone uploads a 10mb jpg avatar? then it'll load slow

**Comment by jimmybisenius** [comment]
I'll look into webp once we add S3 file upload support, closing until then 👍
