### ISSUE TITLE
New Singlelink Community Needed

### ISSUE THREAD

**Issue by UnixPhonez** [Neutron-Creative/Singlelink#215]
Singlelink needs its own community forum or something other than discord...

**Comment by jimmybisenius** [comment]
I'm open to the idea, what could we do with a community forum that we can't do with Discord now?

**Comment by drewpatrickboyle** [comment]
I tend to find forums more searchable and able to create an expanding knowledge-base. Imagine stackoverflow on discord. It wouldn’t work

**Comment by UnixPhonez** [comment]
> I'm open to the idea, what could we do with a community forum that we can't do with Discord now?

Allow users to easily search for questions on a forum, and it's not possible with discord. It's a little more professional, especially once you get to a bigger audience base, discord is going to be hard to keep up with all the questions. A forum has SEO ranking bringing in more users, also potentially paying users.

**Comment by jimmybisenius** [comment]
Okay, this sounds great. Ironically, I'm going to move this discussion back to Discord to allow our userbase to vote on a forum for us to use. Closing this issue, but let's continue the discussion there! 👍
