### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Singlelink#220]

**Comment by LeoColman** [comment]
Hey!
I started doing some work on this in my personal stack:
https://github.com/LeoColman/MyStack/tree/main/singlelink

I've managed to get Singlelink to run in that docker-compose file. I still need to tweak the details, but do you think that's about what you want?

**Comment by jimmybisenius** [comment]
Thanks for the PR! I will take a look and update you by the end of the week 👍

**Comment by jimmybisenius** [comment]
https://github.com/Neutron-Creative/Singlelink/pull/241

**Comment by jimmybisenius** [comment]
Docker support is merged with production. Thanks again, getting apollo to work with NextJS was a pain in the ass!!!
