### ISSUE TITLE
Add draggable link position adjustment and remove manual position fields

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Singlelink#226]

**Comment by sayhijordy** [comment]
This would be amazing.

**Comment by jimmybisenius** [comment]
This will be out later tonight!

**Comment by jimmybisenius** [comment]
PR is out, testing now @sayhijordy
https://github.com/Neutron-Creative/Singlelink/tree/draggable-position

**Comment by jimmybisenius** [comment]
Works - merging!
