### ISSUE TITLE
Remove SSL from server

### ISSUE THREAD

**Issue by NavidK0** [Neutron-Creative/Singlelink#48]

**Comment by jimmybisenius** [comment]
Pretty sure this broke the 2.0 beta? - see attached image
<img width="1440" alt="Screen Shot 2020-10-22 at 1 56 34 AM" src="https://user-images.githubusercontent.com/6027238/96831030-53050b00-140a-11eb-9c69-d9cc0064a120.png">

**Comment by NavidK0** [comment]
The server was down, not related to the issue in the end.
