### ISSUE TITLE
Handle Exists Exception

### ISSUE THREAD

**Issue by wyamout** [Neutron-Creative/Singlelink#51]
At the moment Chrome automatically refills the generated slug with a previously used slug. I think a validation error show be showing when trying to save an existing handle. Now it just refreshes and refills the auto-generated handle but then Chrome refills the previously used one again for me.

**Comment by jimmybisenius** [comment]
Great thought @wyamout . Will have this in with 2.2!

**Comment by NavidK0** [comment]
Resolved with d2a58eeae5e8cbc2a4ecf55cf4f603420d5ba6ea.
