### ISSUE TITLE
Accounts List

### ISSUE THREAD

**Issue by wyamout** [Neutron-Creative/Singlelink#52]
Would be great if there is a page with a  list of accounts table with search, coz now an someone with 20 accounts the pull up menu of accounts is not user friendly, I added 20 accounts and I can't get to the first ones anymore and there is no scroll.

**Comment by jimmybisenius** [comment]
I'll be honest @wyamout , we didn't ever think someone would have a need for 20+ profiles!

We're glad you're using Singlelink, we'll have this done ASAP!!!

Don't want you locked out of those profiles for long.

In the meantime, if there's any profile you need to access, let me know the handle and I'll set it as your active profile!

**Comment by wyamout** [comment]
@jimmybisenius yes we are using Singlelink and it's awesome thank you for the effort. 
`In the meantime, if there's any profile you need to access, let me know the handle and I'll set it as your active profile!`

no need, for now, I'm just changing CSS in the browser 👍

**Comment by NavidK0** [comment]
Added with https://github.com/Neutron-Creative/Singlelink/commit/d4b0a69a85e19ab97670d0054e6830f43f77fd37
