### ISSUE TITLE
Even after removing Headline and Subtitle, the website does not update.

### ISSUE THREAD

**Issue by AnimeshRy** [Neutron-Creative/Singlelink#55]
After removing the Headline or the Subtitle from the dashboard, this does not remove the name and tagline from the website. 
Tried it on multiple devices.

![Singlelink - A free   open-source Linktree alternative - Brave 27-10-2020 17_42_58](https://user-images.githubusercontent.com/54435702/97300143-0b540880-187c-11eb-8b5b-0a3abbe7fc55.png)

**Comment by jimmybisenius** [comment]
Hey @AnimeshRy !

Great catch. I've manually wiped this information for you from your profile now, but I've added this to the upcoming 2.1 sprint as well as a bug fix.

Appreciate you helping to maintain Singlelink!

PS: A headline might still show per the default settings, but this can be fixed via the following code in the custom CSS input!
> .sl-headline {display:none !important;}

**Comment by NavidK0** [comment]
This is fixed in the future-update branch with e0f7bdd505ff2bc5458a0da334cdf852cc1d731f.
