### ISSUE TITLE
Thumbnail.js returns twice, second return never used

### ISSUE THREAD

**Issue by drewpatrickboyle** [Neutron-Creative/Singlelink#58]
"    } finally {
        //return res.send(btoa(thumbnail.data));

        let thumbnail_img = "data:" + thumbnail.headers["content-type"] + ";base64," + Buffer.from(thumbnail.data).toString('base64');

        res.writeHead(200, {
            'Content-Type': 'image/png',
            'Content-Length': thumbnail.data.length
        });
        return res.end(thumbnail.data);
        return res.sendFile(thumbnail.data);

    }
};" 

Everything after the first return will never be called.

**Comment by drewpatrickboyle** [comment]
"Unreachable code"

**Comment by NavidK0** [comment]
Resolved in the future-update branch.
