### ISSUE TITLE
Add user consent modal

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Singlelink#67]
Add & force one-time user consent modal on sign-in for existing users, as well as on sign-up for new users.

**Comment by jimmybisenius** [comment]
Added privacy policy in b155c30e4d6cbeb0c1ca2da256352259b9d15244 , awaiting implementation from @NavidK0

**Comment by jimmybisenius** [comment]
Please ensure GDPR consent modal is added as well! 👍

**Comment by NavidK0** [comment]
Added with f1e2b5a91f3a7af05a8b0798b908e32518daaff3.
