### ISSUE TITLE
Add mailto link support

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Singlelink#69]
Add support for mailto links/per-link privacy mode - currently, they break with the analytics overlay used by default.

**Comment by NavidK0** [comment]
Mailto links appear to work correctly, and analytics are correctly counted.

Tested with this URL: `mailto:test@gmail.com?subject=This%20is%20a%20test&body=Hello%20world%2C%20this%20is%20a%20test`

**Comment by jimmybisenius** [comment]
You are the MAN!!! Was just thinking of this last night.
