### ISSUE TITLE
Profile input edit bug on Mozilla Firefox

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Singlelink#73]
Reported from user:

![bug-singlelink](https://user-images.githubusercontent.com/6027238/101443334-33a73c00-38eb-11eb-9a84-81c24c3eabee.png)
![bug-singlelink-2](https://user-images.githubusercontent.com/6027238/101443342-373ac300-38eb-11eb-8df4-068475f45385.png)
![bug-singlelink-3](https://user-images.githubusercontent.com/6027238/101443345-39048680-38eb-11eb-8c01-402ed2593974.PNG)

**Comment by NavidK0** [comment]
I have not been able to reproduce this on the future-branch, so it might be fixed with the latest updates. Please reopen/comment on this issue if this is still a problem after the latest update goes live.
