### ISSUE TITLE
Integrate new deep link service

### ISSUE THREAD

**Issue by NavidK0** [Neutron-Creative/Singlelink#87]
Instead of using Deep Link, we will switch to using a service such as switchy.io where the user will provide an API key or something similar.

Maintaining deep links for all the various intent URLs requires a significant portion of dev time, so it needs to be outsourced.

**Comment by jimmybisenius** [comment]
@NavidK0 - can we delay this until the marketplace is ready, then make it a plugin? Think it has a lot better fit as an optional add-on since it's not a first-party service.
