### ISSUE TITLE
Move profile & user fetch to async data in profile component to fix server-side rendering of dynamic content.

### ISSUE THREAD

**Issue by jimmybisenius** [Neutron-Creative/Singlelink#94]
Currently, profile & user data are fetched client-side via AJAX on page load, which broke profile SEO, client-side javascript, and more.

We need to move the profile/user/links fetch to async data so they run before the page is rendered to the client/search engines to ensure consistent content display across all environments.

**Comment by NavidK0** [comment]
This should happen now with https://github.com/Neutron-Creative/Singlelink/commit/0556a104de570dee9d1a98a36c00fae3792b102b.
