### ISSUE TITLE
No analytics

### ISSUE THREAD

**Issue by andrewperry** [Neutron-Creative/Singlelink#96]
I just signed up for an account at https://app.singlelink.co/ but when I go to the created page at https://app.singlelink.co/u/andrewperry I am not seeing the statistics for page views or link clicks change at https://app.singlelink.co/dashboard/analytics

I have tried viewing the page through an incognito window in case it ignores clicks from the logged in administrator and also from a mobile device on a different network. Still showing 0 views and 0 clicks.

This may be your service setup issue as much as a code issue?

I was using Chrome on the desktop and Safari on the phone.

**Comment by jimmybisenius** [comment]
Hey @andrewperry, we resolved this with our latest update.

Let us know if there's anything else we can help you with!
